-- MySQL Script generated by MySQL Workbench
-- Sun Jun 15 19:44:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema buyhub_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema buyhub_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `buyhub_db` DEFAULT CHARACTER SET utf8 ;
USE `buyhub_db` ;

-- -----------------------------------------------------
-- Table `buyhub_db`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buyhub_db`.`stock` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT(512) NOT NULL,
  `price` FLOAT NOT NULL,
  `available` INT NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buyhub_db`.`product_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buyhub_db`.`product_photo` (
  `photo_id` INT NOT NULL AUTO_INCREMENT,
  `photo` MEDIUMBLOB NULL DEFAULT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`photo_id`),
  INDEX `fk_fotos_articulos_Stock_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_fotos_articulos_Stock`
    FOREIGN KEY (`product_id`)
    REFERENCES `buyhub_db`.`stock` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buyhub_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buyhub_db`.`users` (
  `user_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `paternal_surname` VARCHAR(100) NOT NULL,
  `maternal_surname` VARCHAR(100) NULL DEFAULT NULL,
  `birthday` DATETIME NOT NULL,
  `phone_number` BIGINT NULL DEFAULT NULL,
  `session_token` VARCHAR(20) NULL DEFAULT NULL,
  `session_expires` DATETIME NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `usuarios_1` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buyhub_db`.`bag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buyhub_db`.`bag` (
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `amount` INT NOT NULL DEFAULT 1,
  INDEX `fk_carrito_compra_stock1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_carrito_compra_usuarios1` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`product_id`, `user_id`),
  CONSTRAINT `fk_carrito_compra_usuarios1`
    FOREIGN KEY (`user_id`)
    REFERENCES `buyhub_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_compra_stock1`
    FOREIGN KEY (`product_id`)
    REFERENCES `buyhub_db`.`stock` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `buyhub_db`.`user_photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buyhub_db`.`user_photo` (
  `id_photo` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `photo` MEDIUMBLOB NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id_photo`, `user_id`),
  INDEX (`user_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`user_id`)
    REFERENCES `buyhub_db`.`user` (`user_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
