-- MySQL Script generated by MySQL Workbench
-- Thu Jun  5 19:56:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema servicio_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema servicio_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `servicio_web` DEFAULT CHARACTER SET utf8 ;
USE `servicio_web` ;

-- -----------------------------------------------------
-- Table `servicio_web`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicio_web`.`stock` (
  `id_articulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(64) NOT NULL,
  `descripcion` TEXT(512) NOT NULL,
  `precio` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_articulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicio_web`.`fotos_articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicio_web`.`fotos_articulos` (
  `id_foto` INT NOT NULL AUTO_INCREMENT,
  `foto` MEDIUMBLOB NULL DEFAULT NULL,
  `id_articulo` INT NOT NULL,
  PRIMARY KEY (`id_foto`),
  INDEX `fk_fotos_articulos_Stock_idx` (`id_articulo` ASC) VISIBLE,
  CONSTRAINT `fk_fotos_articulos_Stock`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `servicio_web`.`stock` (`id_articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicio_web`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicio_web`.`usuarios` (
  `id_usuario` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido_paterno` VARCHAR(100) NOT NULL,
  `apellido_materno` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `telefono` BIGINT NULL DEFAULT NULL,
  `password` VARCHAR(20) NOT NULL,
  `token` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuarios_1` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicio_web`.`carrito_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicio_web`.`carrito_compra` (
  `id_usuario` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  `cantidad` INT NOT NULL DEFAULT 1,
  INDEX `fk_carrito_compra_stock1_idx` (`id_articulo` ASC) VISIBLE,
  INDEX `fk_carrito_compra_usuarios1` (`id_usuario` ASC) VISIBLE,
  PRIMARY KEY (`id_articulo`, `id_usuario`),
  CONSTRAINT `fk_carrito_compra_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `servicio_web`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_compra_stock1`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `servicio_web`.`stock` (`id_articulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicio_web`.`fotos_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicio_web`.`fotos_usuarios` (
  `id_foto` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `foto` MEDIUMBLOB NULL DEFAULT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_foto`, `id_usuario`),
  INDEX (`id_usuario` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_usuario`)
    REFERENCES `servicio_web`.`usuarios` (`id_usuario`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
